### ISSUE TITLE
Crashes on server

### ISSUE THREAD

**Issue by SamhitApple** [Pyxrs/CampingMod#14]
**Crash Report:** https://pastebin.com/C4z01cJ6

**Comment by Pyxrs** [comment]
I honestly have no idea why this crash is happening, I've never seen anything like it.

One fix you could try is using
`Fabric Api 0.37.2+1.17`
and
`Fabric Loader 0.11.6`

**Comment by SamhitApple** [comment]
Still crashes when I load just Fabric API and Simply Camping (Fabric Installer is 0.12.1)
Crash Report: https://pastebin.com/XrBRUPMR
