### ISSUE TITLE
Brown Bears are looking great! When compared to vanilla Polar Bears there are so minor things to consider changing.

### ISSUE THREAD

**Issue by K0-RR** [Pyxrs/CampingMod#3]
Vanilla Bears are longer and have the body made of two parts, one slightly thicker. Also your brown bear texture could be a bit recolored (I'm sorry but it reminds me about badly compressed images because of  the harsh change between colors on the bear's back)
 
![Screenshot from 2021-08-31 12-52-08](https://user-images.githubusercontent.com/43277609/131490514-f5af0416-79aa-4f82-8d81-2817094b8c1c.png)
![Screenshot from 2021-08-31 12-52-14](https://user-images.githubusercontent.com/43277609/131490520-8e832319-c850-4d65-acf8-185ef1d8da3a.png)
![Screenshot from 2021-08-31 12-52-25](https://user-images.githubusercontent.com/43277609/131490523-d3ae229f-a1b9-42f8-9b86-c31492f93e1a.png)

Btw you have chosen great color maps for leaves and grass!

Not sure if this is a bug so reporting it here too - trees generated floating:
![Screenshot from 2021-08-31 12-46-55](https://user-images.githubusercontent.com/43277609/131491489-67932075-2df7-443b-b249-5f5114a02b1d.png)

**Comment by Pyxrs** [comment]
Brown bear will not be changed but its color palette may undergo a change. The floating trees bug has been in Minecraft for a while and _should_ have been fixed in 1.17 but it was not. I think it may instead be an issue with the API we're using, in which case I may be able to fix

**Comment by Pyxrs** [comment]
I'm probably not going to end up fixing the floating trees bug since it's such a minor issue
