### ISSUE TITLE
How to obtain sap and what to do with it? How to craft marshmallows? What's the use of cloth?

### ISSUE THREAD

**Issue by K0-RR** [Pyxrs/CampingMod#5]
Also, please don't add backpacks or add config to disable them as there are many mods for backpacks already.

**Comment by Pyxrs** [comment]
I recommend the use of external recipe mods such as Roughly Enough Items: https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
or using the command `/recipe give @s *`
to view recipes, although I wiki will likely be made in the future
