### ISSUE TITLE
biomes

### ISSUE THREAD

**Issue by Chuunkyz** [Pyxrs/CampingMod#6]
can you please make the biomes rarer ? or maybe make a config to set the biome weights ?
cuz there's way too many forests from this mod

**Comment by Pyxrs** [comment]
This was an intended feature to showcase the mod's features, but in future updates, it will be fixed.

**Comment by supersaiyansubtlety** [comment]
This basically makes the mod unusable in survival. 
After installing, ~90% of all area in newly generated chunks was pine forest.

**Comment by Pyxrs** [comment]
Agreed, the mod was originally made as a part of a competition, so we wanted the features to be obvious. However, now that the mod has been published, it will revert to a realistic biome amount

**Comment by Pyxrs** [comment]
Updated in the upcoming release, "1.0.1"
