### ISSUE TITLE
Crash with RPG stats

### ISSUE THREAD

**Issue by AlisterGontineac** [Pyxrs/CampingMod#9]
If I remove RPG stats ( https://www.curseforge.com/minecraft/mc-mods/rpgstats ) and leave in Simply camping it launches fine, and vice versa, but if I load them together the game won't launch.

Crash log
https://paste.ee/p/qykOA

**Comment by Pyxrs** [comment]
Ah, that's due to the fishing mixin using overwrite instead of inject, which can be fixed
